### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by hulapyk** [Bluscream/GTACoop#20]
Hi,
I've set up a server and had it running, it seems to be working fine, but when I or friend of mine tries to join, we get a message saying it couldn't connect.
In the serverlog/command prompt it gives this error:
**(ERROR) SERVER: Can't handle tick: System.NullReferenceException: Object reference not set to an instance of an object.
   at GTAServer.GameServer.Tick()**

**Comment by rabi31001** [comment]
did you fix that bro ? i have the same problem
