### ISSUE TITLE
I can't start up my own server

### ISSUE THREAD

**Issue by Control2** [Bluscream/GTACoop#22]
Every time I setup a server I can't connect to it and I know I setup the port forwarding correctly but every time I try and connect I get this error [9/22/2016 11:05:35 AM](ERROR) SERVER: Can't handle tick: System.NullReferenceException: Object reference not set to an instance of an object.
   at GTAServer.GameServer.Tick() 
or when I try with out it, it will say object reference not set to an instance of an object.... _this I don't use the GTAServer.exe and I try to set it up in game_

**Comment by Control2** [comment]
Ok I fixed it, but I cant make it private which I can live with

**Comment by Bluscream** [comment]
Thanks, what do you mean by 'cant make it private'

**Comment by rabi31001** [comment]
how did you fix that ?

**Comment by Chazz-K** [comment]
I'm getting the same error, how do you fix it?

**Comment by soccermitchy** [comment]
Is this all that is in the error? Does it give any other information like a file name or line number for where it happened? Without that or a way to reproduce the error, I can't do much.
