### ISSUE TITLE
plz do a guide

### ISSUE THREAD

**Issue by shaharpro** [Bluscream/GTACoop#24]
plz send me a full guide how to install this mod

**Comment by Bluscream** [comment]
@shaharpro There is no "Guide". You can look up Frequently Asked Questions in the [wiki](https://github.com/Bluscream/GTACoop/wiki) or ask questions directly to us here on [github](https://github.com/Bluscream/GTACoop/issues/new) or on our [discord](https://discord.gg/ww7DthF) server :)
