### ISSUE TITLE
Cant start server on 0.9.3 tells me to "upgrade" to 0.9.1

### ISSUE THREAD

**Issue by Sharpshooter093** [Bluscream/GTACoop#27]
Ok me and my friend have been just trying to make a simple server so both of us can freeroam. Not so hard, well so i thought. whenever i start the server and then try to connect to it in the game it says i need to update to 0.9.1 when im on 0.9.3. how is that updating, more like downgrading. So i give it the benifit of the doubt and download 0.9.1 and install everything....and i get the same message saying update to 0.9.1 when it clearly says im on that version. i dont understand this. been trying for 3 days to just make a simple no password server so both me and my friend can join. any help would be greatly appreciated.

**Comment by Bluscream** [comment]
@Sharpshooter093 get the latest client and set the local client version to 0.9.1 from within the F9 Settings.
