### ISSUE TITLE
[HELP]F9 is not working !

### ISSUE THREAD

**Issue by ADoKaN** [Bluscream/GTACoop#33]
Hello guys..
When I press F9 nothing appears tell me if the mod work only for original versions and If it works with cracked versions too please tell me how to fix it !
I really need help from you guys.. it will be much appreciated !
~Regards

**Comment by Dhrhciebcy** [comment]
You must have Microsoft Visual C++ 2013 on your computer, then SriptHookV, ScriptHookVDotNet and Lua (these are mods loaders for GTA V).

**Comment by ADoKaN** [comment]
It worked thanks but I'm having another problem !
When I try to connect to a server it tells me to update your Co-op to v0.9.3 and I already Updated it !
Any solution?

**Comment by soccermitchy** [comment]
Two things wrong with your last comment:
1. Open another issue if this one is fixed and you have a different one
2. There already is another issue with this reported - see #27

**Comment by Bluscream** [comment]
#14
