### ISSUE TITLE
Linux Version...

### ISSUE THREAD

**Issue by treboR-0** [Bluscream/GTACoop#35]
I need a version and tutorial, for this always fun mod, to setup on a CentOS 7.2 VPS.

Also you should default all NPC Traffic shares to off, please....

**Comment by soccermitchy** [comment]
Works on linux perfectly fine with mono. Don't know how to do it on CentOS, but on Debian/Ubuntu, you can just do `sudo apt-get install mono-complete`, extract GTAServer to a folder, and do `mono GTAServer.exe`, which is exactly what I did in my test server deployment scripts (auto-deployed to a fresh VM with debug tools installed)

**Comment by treboR-0** [comment]
Thanks :)
