### ISSUE TITLE
Trojan?

### ISSUE THREAD

**Issue by ThorbenManfred** [Bluscream/GTACoop#40]
Why does my Antivir tell me that its a trojan?

**Comment by Bluscream** [comment]
Which Anti Virus software do you use?

**Comment by ThorbenManfred** [comment]
360 Total Security

**Comment by Bluscream** [comment]
https://www.virustotal.com/en/file/fb08a0bc6191ae5df729046cf0b11fc6bd9bba63a604358c7bc86a8ec33e47a2/analysis/1480361008/

https://www.virustotal.com/en/file/383e046d2fc5c64927bf21e65defbf7bc61c12a39869647661c125941786444f/analysis/1480361006/

**Comment by Bluscream** [comment]
Can you show a screenshot of the virus alert?

**Comment by ThorbenManfred** [comment]
I think is was a bit like this: https://dieviren.de/wp-content/uploads/virusai/360-total-security-virus-3_de.jpg
It easily put it into quarantine but I took it out of the quarantine and now i have bad feeling

**Comment by Bluscream** [comment]
I need to see the actual full virus alert/report to help you.

**Comment by ThorbenManfred** [comment]
Are u German?

**Comment by ThorbenManfred** [comment]
![screenshot 62](https://cloud.githubusercontent.com/assets/24232342/20683813/b8570392-b5ad-11e6-8b2b-4b715a403176.png)

**Comment by ThorbenManfred** [comment]
Well thats the exact message

**Comment by Bluscream** [comment]
Thanks for the screenshot. I will investigate it and write a false-positive report tomorrow :)

**Comment by JohnHawkinsWei** [comment]
Man, 360 Total Security is nothing but BULLSHIT, it is just a trojan itself. It always scanning ur computer collecting even ur web searching keywords, package and upload the information to their server, unload/disable software from their competitors without user's permission. u can't even uninstall it clearly from ur operating system. And the ceo of 360 is just the guy who made the earliest malware named 3721 web-surfing tool, i highly  suggest u trying other anti-virus software. ;\

**Comment by Bluscream** [comment]
![tmp_4946-screenshot_20161203-1958181374928373](https://cloud.githubusercontent.com/assets/3318223/20861539/e28df45c-b992-11e6-8376-2fd81c3b2490.png)

**Comment by Bluscream** [comment]
<div class="bodycontainer">

<table border="0" cellspacing="0" cellpadding="0" width="100%">

<tbody>

<tr height="14px">

<td width="143">![Gmail](//www.gmail.com/mail/help/images/logonew.gif)</td>

<td align="right"><font color="#777" size="-1">**Hans Peter <omitomit1@gmail.com>**</font></td>

</tr>

</tbody>

</table>

* * *

<div class="maincontent">

<table border="0" cellspacing="0" cellpadding="0" width="100%">

<tbody>

<tr>

<td><font size="+1">**Thank you for your submission**</font>  
<font color="#777" size="-1">1 message</font></td>

</tr>

</tbody>

</table>

* * *

<table class="message" border="0" cellspacing="0" cellpadding="0" width="100%">

<tbody>

<tr>

<td><font size="-1">**no-reply@ucmail.360.cn** <no-reply@ucmail.360.cn></font></td>

<td align="right"><font size="-1">Mon, Dec 5, 2016 at 10:30 AM</font></td>

</tr>

<tr>

<td colspan="2"><font class="recipient" size="-1">

<div>To: admin@timo.de.vc</div>

</font></td>

</tr>

<tr>

<td colspan="2">

<table border="0" cellspacing="0" cellpadding="12" width="100%">

<tbody>

<tr>

<td>

<div style="overflow: hidden;"><font size="-1">

<div>

<table style="border-bottom:1px solid #ccc" cellspacing="10" bgcolor="#FFFFFF" align="center" width="686">

<tbody>

<tr>

<td>![](https://ci3.googleusercontent.com/proxy/4BL5q8iFKpxZUKjPsw7OR1SN908ijNFOfhEBo1NmFumYf5Sm-vulQb7PFFF5Ooa-7u5qwFcVlgtelMNjzR0nFDtxJgHJH4o=s0-d-e1-ft#http://p5.qhimg.com/d/inn/125bd804/logo_360TS.png)</td>

<td align="right">[www.360totalsecurity.com](http://www.360totalsecurity.com/)</td>

</tr>

</tbody>

</table>

<table border="0" cellspacing="10" cellpadding="0" bgcolor="#FFFFFF" align="center" width="686">

<tbody>

<tr>

<td>

Dear Sir or Madam,

</td>

</tr>

<tr>

<td>

The file that you’ve submitted has been analyzed(Time: 2016-12-04 03:00:04; Software: tmp_4946-Client-233216691; ID:2697558).

We sincerely appreciate your help of improving our products and services.

Result: Proper actions have been taken. If the false positive happens again, please add it into local Trust List and contact us again with [support@360safe.com](mailto:support@360safe.com) .

Thanks for your support.

</td>

</tr>

</tbody>

</table>

<table style="border-top:1px solid #ccc" cellspacing="10" bgcolor="#FFFFFF" align="center" width="686">

<tbody>

<tr>

<td>Please do not reply to this email. In case of any questions or doubts, please contact [support@360safe.com](mailto:support@360safe.com)</td>

</tr>

<tr>

<td align="right">360 Total Security</td>

</tr>

<tr>

<td align="right">2016-12-05 17:30:32</td>

</tr>

</tbody>

</table>

</div>

</font></div>

</td>

</tr>

</tbody>

</table>

</td>

</tr>

</tbody>

</table>

</div>

</div>

<script type="text/javascript">// <![CDATA[ document.body.onload=function(){document.body.offsetHeight;window.print()}; // ]]></script>

**Comment by ThorbenManfred** [comment]
Thx
