### ISSUE TITLE
Server is port forwarded but no one can join?

### ISSUE THREAD

**Issue by paustin123** [Bluscream/GTACoop#45]
When either my friend or me opens a server we cant join each other.

**Comment by paustin123** [comment]
Never mind people can join but he cant through my ip? I dont know how people are joining?

**Comment by paustin123** [comment]
Ok this need to be placed in the instructions as im having to google everything else to fix problems with this mod. If youre using mod manager you have to uncheck the firefall rule.

**Comment by Bluscream** [comment]
True
