### ISSUE TITLE
Master Server

### ISSUE THREAD

**Issue by Segeco** [Bluscream/GTACoop#8]
Master Server down? Can we have a new IP? :)

**Comment by soccermitchy** [comment]
My personal server is down, otherwise I would be hosting my own for the mod. Should be back up within a week though.

**Comment by Bluscream** [comment]
I can prove a temporary one if you push it for me :P

**Comment by soccermitchy** [comment]
I'll just host my own since my modifications to the server probably won't be done until my server is up anyway. Especially since I just got a ticket reply from my host saying that it'd probably be up today.

**Comment by Bluscream** [comment]
@soccermitchy @Segeco `http://gtacoop.ddns.net:5000/`

**Comment by soccermitchy** [comment]
You should now be able to set your master server to `gtamaster.nofla.me`, although there aren't any servers on it right now.
